version: "2"
services:

  one-network-integration-service:
    image: openlmis/one-network-integration-service
    links:
      - db
      - log
    env_file: .env

  db:
    image: openlmis/postgres:9.6
    ports:
      - "5432"
    env_file: .env

  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/one-network-integration-service:/var/log'
